language: java
dist: trusty
sudo: required
jdk:
  - oraclejdk8
services:
  - docker
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar;
  - docker build -t "$DOCKER_USERNAME/insurance-api" .;
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push "$DOCKER_USERNAME/insurance-api:latest";